<?php $social_media_settings = get_social_media_settings(); ?>
<div class="cs-social">
    <a class="cs-social__link" href="<?= esc_url($social_media_settings['facebook']); ?>" target="_blank">
        <img data-src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001.png" alt="Facebook" data-srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001@2x.png 2x" src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001.png" class=" ls-is-cached lazyloaded" srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-facebook-0001@2x.png 2x">
    </a>
    <a class="cs-social__link" href="<?= esc_url($social_media_settings['twitter']); ?>" target="_blank">
        <img data-src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001.png" alt="Twitter" data-srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001@2x.png 2x" src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001.png" class=" ls-is-cached lazyloaded" srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-twitter-0001@2x.png 2x">
    </a>
    <a class="cs-social__link" href="<?= esc_url($social_media_settings['instagram']); ?>" target="_blank">
        <img data-src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001.png" data-srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001@2x.png 2x" alt="Instagram" src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001.png" class=" ls-is-cached lazyloaded" srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-instagram-0001@2x.png 2x">
    </a>
    <a class="cs-social__link" href="<?= esc_url($social_media_settings['youtube']); ?>" target="_blank">
        <img data-src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001.png" data-srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001@2x.png 2x" alt="Youtube" src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001.png" class=" ls-is-cached lazyloaded" srcset="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001.png 1x, <?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-youtube-0001@2x.png 2x">
    </a>
    <a class="cs-social__link" href="<?= esc_url($social_media_settings['truth']); ?>" target="_blank">
        <img data-src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-social-truth.png" alt="Truth" src="<?php echo get_template_directory_uri(); ?>/assets/assets/uploads/2024/04/icon-social-truth.png" class=" ls-is-cached lazyloaded"> </a>
</div>